const salesContent = {
  en: {
    productName: 'PapayaMusic Lab Studio',
    brandSubtitle: 'Studio',
    nav: {
      tour: 'Product tour',
      fit: 'Fit',
      pilot: 'Pricing',
      faq: 'FAQ',
      blog: 'Blog',
      docs: 'Buyer guide',
    },
    a11y: {
      home: 'PapayaMusic Lab home',
      primaryNav: 'Primary navigation',
      language: 'Language selector',
      footerNav: 'Footer navigation',
    },
    hero: {
      eyebrow: 'For solo creators and small studios releasing AI music',
      title: 'Made a strong AI song? Finish the release.',
      lead:
        'PapayaMusic Lab Studio connects track selection, mastering checks, distributor metadata, music-video work, and YouTube preparation in one local Windows workflow.',
      primaryCta: 'See the 90-second workflow',
      secondaryCta: 'See if it fits my work',
      platform: 'Founder Pilot · Windows 11',
      proof: ['Unreleased audio and video stay local', 'Use your existing Suno, REAPER, DistroKid, and YouTube accounts', 'You approve selection, rights, and final submission'],
    },
    tour: {
      eyebrow: '90-second product tour',
      title: 'Choose the track. Check the work. Finish the release.',
      lead:
        'The production record carries your decisions and readiness forward, so every tool does not become another place to start over.',
      previewLabel: 'Product workflow example · dummy data',
      stages: [
        {
          step: '01',
          title: 'Keep only the tracks worth finishing',
          text: 'Review generated takes, keep the release candidates, and preserve why they moved forward.',
          screenTitle: 'Candidate review',
          status: '8 release candidates',
          rows: [
            ['Track rating', 'S / A / B'],
            ['Production context', 'Saved'],
            ['Next action', 'Visible'],
          ],
        },
        {
          step: '02',
          title: 'Check the master and release details',
          text: 'Review measurable mastering evidence, filenames, metadata, credits, and missing materials before handoff.',
          screenTitle: 'Release readiness',
          status: '4 of 5 checks complete',
          rows: [
            ['Mastering QC', 'Ready'],
            ['Distributor metadata', 'Review'],
            ['Rights and credits', 'Human check'],
          ],
        },
        {
          step: '03',
          title: 'Close the publishing work',
          text: 'Prepare the distributor handoff, music video, and YouTube materials while keeping final submission manual.',
          screenTitle: 'Publishing package',
          status: 'Awaiting final approval',
          rows: [
            ['DistroKid handoff', 'Ready'],
            ['Music video', 'Approved'],
            ['YouTube copy', 'Review'],
          ],
        },
      ],
      disclosure: 'This example uses dummy data. Product details may change during the pilot.',
    },
    fit: {
      eyebrow: 'Who it is for',
      title: 'It fits when this problem keeps coming back.',
      lead: 'Founder Pilot is for people who create AI music regularly but accumulate candidates and follow-up work faster than finished releases.',
      goodTitle: 'Likely a good fit',
      goodItems: [
        'You manage roughly 30 or more generated candidates in a typical month.',
        'Selection, notes, media, and publishing readiness are spread across folders, chat, and spreadsheets.',
        'You want a local Windows workflow while keeping final creative and publishing approval human.',
      ],
      notTitle: 'Probably not yet',
      notItems: [
        'You need a music generator, DAW, distributor, or done-for-you production service.',
        'Your main machine is macOS or mobile; the current pilot build is Windows-only.',
        'You generate occasionally and do not yet feel a repeatable post-generation bottleneck.',
      ],
    },
    offer: {
      eyebrow: 'Founder Pilot offer',
      title: 'Use the first 30 days to review one real release workflow.',
      lead: 'The application is a fit check, not a checkout. You pay only after the Windows machine, support scope, access, and written terms are confirmed.',
      price: 'USD 199',
      period: 'First 30 days',
      terms: [
        ['Continued access', 'USD 69 per additional 30 days'],
        ['Renewal', 'Manual only; no automatic charge'],
        ['Platform', 'Windows desktop; exact compatibility confirmed before payment'],
      ],
      includesTitle: 'Included in the first 30 days',
      includes: [
        'Fit check for your Windows machine and current tools',
        'Protected Windows build and license after payment',
        'Guided local workspace and prerequisite setup',
        'One review of a real production workflow',
      ],
      processTitle: 'What happens next',
      process: [
        ['1', 'Apply', 'Share the bottleneck, production volume, and target Windows machine.'],
        ['2', 'Confirm', 'Receive a written fit, price, support, access, and refund-terms summary.'],
        ['3', 'Start', 'Pay only if you accept the terms, then receive protected access and setup guidance.'],
        ['4', 'Review', 'Use one real production run to decide whether another 30 days is worthwhile.'],
      ],
      note: 'The written offer provided before payment controls device, continued-access, support, and refund details.',
      cta: 'Apply for Founder Pilot',
    },
    faq: {
      eyebrow: 'Buyer FAQ',
      title: 'Answers before a sales conversation.',
      items: [
        ['Is PapayaMusic Lab Studio another music generator?', 'No. It connects the work around your existing tools: candidate review, mastering evidence, distributor metadata, music-video production, and publishing preparation.'],
        ['Which platforms are supported?', 'The current pilot build is for Windows desktop. Exact Windows version and machine compatibility are checked before payment. macOS and mobile access are not offered in the current pilot.'],
        ['What stays on my computer?', 'Unreleased audio, lyrics, video clips, project files, local paths, browser sessions, and third-party credentials stay local by default unless you explicitly export limited diagnostics for support.'],
        ['Are Suno, ChatGPT, REAPER, distribution, or video accounts included?', 'No. You bring your own accounts and licenses. Tool names describe workflow compatibility and do not imply a partnership.'],
        ['What does USD 199 include?', 'The first 30 days include the fit confirmation, protected access after payment, license activation, guided setup, and one supported production review.'],
        ['What happens after 30 days?', 'There is no automatic renewal. Continued access can be extended manually at USD 69 per 30 days. The written offer confirms the exact access and update terms before payment.'],
        ['What is the refund policy?', 'The applicable refund conditions are stated in the written offer before payment. No payment is requested until you have reviewed and accepted those terms.'],
        ['What is outside support scope?', 'Unlimited production labor, legal advice, third-party account administration, and guaranteed AI output quality are outside the pilot scope.'],
      ],
    },
    operator: {
      eyebrow: 'Operator',
      title: 'A founder-led pilot with a public point of contact.',
      text: 'PapayaMusic Lab is an independent product project maintained by elecpapaya. Pilot-fit reviews, setup discussions, and product feedback are handled directly; no reseller or outsourced sales team sits between the applicant and the operator.',
      link: 'View the public GitHub profile',
    },
    finalCta: {
      eyebrow: 'Next step',
      title: 'If good tracks keep stopping before release, start there.',
      text: 'Four required fields · about two minutes · no payment starts with the application.',
      primary: 'Check fit in two minutes',
      secondary: 'Review buying terms',
    },
    article: {
      byline: 'PapayaMusic Lab · Production note',
      ctaTitle: 'Does the release work take longer than generation?',
      ctaText: 'See whether the Windows Founder Pilot fits the way you select, finish, and publish AI music.',
      cta: 'Check fit in two minutes',
      relatedTitle: 'Continue reading',
    },
    footer: {
      description: 'A local-first Windows production suite for finishing AI music releases.',
      notice: 'Product access, support, and commercial terms are confirmed in writing before payment.',
      data: 'Data handling',
      terms: 'Terms',
      docs: 'Buyer guide',
      contact: 'Contact',
    },
    pilotPage: {
      platformTitle: 'Before you apply: the current build is Windows-only.',
      platformText: 'Choose the machine you plan to use. Other platforms can still submit interest, but paid access is not currently offered for them.',
      operatingSystemPrompt: 'Choose the machine for this pilot',
      operatingSystems: [
        ['Windows 11', 'Windows 11'],
        ['Other Windows — compatibility check needed', 'Other Windows'],
        ['macOS — interest only, no current build', 'macOS waitlist'],
        ['Other platform — interest only', 'Other platform waitlist'],
      ],
    },
    dataHandling: {
      eyebrow: 'Data handling',
      title: 'What the public website collects and why.',
      lead: 'This page describes the current contact and Founder Pilot forms. It is a practical data-handling notice, not a substitute for terms provided with paid product access.',
      updated: 'Last updated: July 16, 2026',
      sections: [
        ['Information you submit', ['Contact forms collect the name, reply email, inquiry type, and message you enter.', 'Founder Pilot applications may also collect role, target operating system, catalog volume, tools, bottleneck, goals, notes, and an optional preference about evidence follow-up.', 'Evidence follow-up consent only permits a later question. No pilot result is published without a separate review and explicit approval.', 'The site may attach the page path, campaign parameters, and referring page path to understand which page led to the inquiry.']],
        ['How it is used', ['Submissions are checked for automated abuse, rate-limited, and forwarded to the private PapayaMusic Lab contact recipient.', 'The information is used to reply, assess pilot fit, clarify support scope, and improve the sales journey.', 'The website does not expose the destination email address in page source.']],
        ['Aggregate journey measurement', ['The site records cookie-free events such as a page or product-tour view, a call-to-action click, form start, operating-system category, and submit outcome.', 'These events contain the language, page path without its query, and controlled category labels. They do not contain form contents, names, email addresses, full referring URLs, cookies, or persistent user identifiers.', 'Aggregate event rows are stored in Cloudflare D1; rows older than 90 days are removed during event collection.']],
        ['Service boundaries', ['Cloudflare Turnstile processes security-check data under Cloudflare’s own terms and privacy documentation.', 'Do not submit passwords, OAuth files, private tokens, unreleased customer data, or confidential media through these forms.', 'Product-local data handling and paid-access terms are explained separately before payment.']],
        ['Your choices', ['You may ask what you previously submitted or request correction or deletion by using the contact form.', 'If you do not want to send the optional production fields, leave them blank.', 'No automatic payment or pilot renewal is triggered by submitting a form.']],
      ],
      contactCta: 'Ask a data-handling question',
    },
  },
  ko: {
    productName: 'PapayaMusic Lab Studio',
    brandSubtitle: 'Studio',
    nav: { tour: '제품 보기', fit: '적합성', pilot: '가격', faq: '자주 묻는 질문', blog: '블로그', docs: '구매 안내' },
    a11y: { home: 'PapayaMusic Lab 홈', primaryNav: '주요 메뉴', language: '언어 선택', footerNav: '하단 메뉴' },
    hero: {
      eyebrow: 'AI 음악을 꾸준히 릴리즈하는 1인 제작자와 소규모 스튜디오를 위해',
      title: '좋은 AI 곡을 만들었다면, 이제 릴리즈까지 끝내세요.',
      lead: 'PapayaMusic Lab Studio는 후보 선별, 마스터링 확인, 배포 정보, 음악 영상과 YouTube 준비를 하나의 Windows 로컬 제작 흐름으로 연결합니다.',
      primaryCta: '90초 작업 흐름 보기',
      secondaryCta: '내 작업에 맞는지 확인',
      platform: 'Founder Pilot · Windows 11',
      proof: ['미공개 음원과 영상은 로컬에 유지', '기존 Suno·REAPER·DistroKid·YouTube 계정 사용', '선별·권리·최종 제출은 직접 승인'],
    },
    tour: {
      eyebrow: '90초 작업 흐름',
      title: '곡을 고르고, 확인하고, 릴리즈까지 끝냅니다.',
      lead: '앱마다 다시 정리하지 않도록 판단 근거와 준비 상태를 다음 작업으로 이어갑니다.',
      previewLabel: '제품 흐름 예시 · 더미 데이터',
      stages: [
        { step: '01', title: '끝낼 가치가 있는 곡만 남깁니다', text: '생성 결과를 검토해 릴리즈 후보를 고르고, 왜 다음 단계로 보냈는지 함께 남깁니다.', screenTitle: '후보 검토', status: '릴리즈 후보 8곡', rows: [['트랙 평가', 'S / A / B'], ['제작 맥락', '저장됨'], ['다음 작업', '확인 가능']] },
        { step: '02', title: '마스터와 배포 정보를 확인합니다', text: '마스터링 수치, 파일명, 메타데이터, 크레딧과 빠진 자료를 전달 전에 검토합니다.', screenTitle: '릴리즈 준비', status: '5개 중 4개 완료', rows: [['마스터링 QC', '준비'], ['배포 메타데이터', '검토'], ['권리·크레딧', '직접 확인']] },
        { step: '03', title: '공개 준비까지 닫습니다', text: '배급사 전달, 음악 영상, YouTube 자료를 준비하되 최종 제출은 직접 승인합니다.', screenTitle: '공개 패키지', status: '최종 승인 전', rows: [['DistroKid 전달', '준비'], ['음악 영상', '승인'], ['YouTube 문구', '검토']] },
      ],
      disclosure: '더미 데이터로 구성한 제품 흐름 예시입니다. 세부 기능은 파일럿 과정에서 달라질 수 있습니다.',
    },
    fit: {
      eyebrow: '누구에게 맞는가', title: '이 문제가 반복될 때 가장 잘 맞습니다.',
      lead: '매달 AI 곡을 만들지만, 완성된 릴리즈보다 후보와 후속 작업이 더 빨리 쌓이는 사용자를 위한 파일럿입니다.',
      goodTitle: '잘 맞을 가능성이 높습니다',
      goodItems: ['평균적으로 월 30개 안팎 이상의 생성 후보를 관리합니다.', '선별, 노트, 미디어, 공개 준비가 폴더·채팅·스프레드시트에 흩어져 있습니다.', 'Windows 로컬 흐름을 원하며 창작과 공개의 최종 승인은 직접 하고 싶습니다.'],
      notTitle: '아직은 맞지 않을 수 있습니다',
      notItems: ['음악 생성기, DAW, 배급사 또는 제작 대행 서비스가 필요합니다.', '주 사용 기기가 macOS나 모바일입니다. 현재 파일럿 빌드는 Windows 전용입니다.', '가끔 생성하며 생성 이후 반복 병목을 아직 느끼지 않습니다.'],
    },
    offer: {
      eyebrow: 'Founder Pilot 제안', title: '첫 30일 동안 실제 릴리즈 흐름 한 번을 함께 점검합니다.',
      lead: '신청은 결제가 아니라 적합성 확인입니다. 사용할 Windows PC, 지원 범위, 접근 방식과 서면 조건을 확인한 뒤에만 결제를 요청합니다.',
      price: 'USD 199', period: '첫 30일',
      terms: [['계속 사용', '추가 30일마다 USD 69'], ['갱신', '수동 선택만 가능 · 자동 결제 없음'], ['플랫폼', 'Windows 데스크톱 · 결제 전 호환성 확인']],
      includesTitle: '첫 30일 포함 내용',
      includes: ['Windows PC와 기존 도구 적합성 확인', '결제 후 보호된 Windows 빌드와 라이선스', '로컬 작업 폴더와 필수 도구 가이드 셋업', '실제 제작 흐름 1회 리뷰'],
      processTitle: '신청 후 진행',
      process: [['1', '신청', '병목, 제작 규모, 사용할 Windows PC를 공유합니다.'], ['2', '확인', '적합성, 가격, 지원, 접근, 환불 조건을 서면으로 받습니다.'], ['3', '시작', '조건에 동의할 때만 결제하고 보호된 접근과 셋업 안내를 받습니다.'], ['4', '검토', '실제 제작 1회를 수행한 뒤 다음 30일이 가치 있는지 판단합니다.']],
      note: '기기, 계속 사용, 지원, 환불의 세부 조건은 결제 전에 제공되는 서면 제안이 기준입니다.', cta: 'Founder Pilot 신청',
    },
    faq: {
      eyebrow: '구매 전 자주 묻는 질문', title: '상담 전에 먼저 확인할 답변입니다.',
      items: [
        ['PapayaMusic Lab Studio는 음악 생성기인가요?', '아닙니다. 기존 도구 사이의 후보 검토, 마스터링 근거, 배포 메타데이터, 음악 영상 제작과 공개 준비를 연결합니다.'],
        ['어떤 운영체제를 지원하나요?', '현재 파일럿 빌드는 Windows 데스크톱 전용입니다. 정확한 Windows 버전과 PC 호환성은 결제 전에 확인합니다. macOS와 모바일 빌드는 현재 제공하지 않습니다.'],
        ['무엇이 내 컴퓨터에 남나요?', '미공개 음원, 가사, 영상 클립, 프로젝트 파일, 로컬 경로, 브라우저 세션, 외부 서비스 자격 정보는 제한된 진단 정보를 지원용으로 직접 내보내지 않는 한 기본적으로 로컬에 남습니다.'],
        ['Suno, ChatGPT, REAPER, 배급이나 영상 계정도 포함되나요?', '아닙니다. 기존 계정과 라이선스를 사용합니다. 도구명은 작업 흐름의 호환성을 설명하며 공식 제휴를 의미하지 않습니다.'],
        ['USD 199에 무엇이 포함되나요?', '첫 30일의 적합성 확인, 결제 후 보호된 접근, 라이선스 활성화, 가이드 셋업, 제작 작업 1회 리뷰가 포함됩니다.'],
        ['30일 뒤에는 어떻게 되나요?', '자동 갱신은 없습니다. 계속 사용은 30일마다 USD 69로 직접 연장할 수 있습니다. 정확한 접근과 업데이트 조건은 결제 전 서면 제안에서 확인합니다.'],
        ['환불 정책은 무엇인가요?', '적용되는 환불 조건은 결제 전에 서면 제안에 명시합니다. 조건을 검토하고 동의하기 전에는 결제를 요청하지 않습니다.'],
        ['지원 범위에 포함되지 않는 것은 무엇인가요?', '무제한 제작 대행, 법률 자문, 외부 계정 관리, AI 결과물 품질 보장은 파일럿 지원 범위 밖입니다.'],
      ],
    },
    operator: {
      eyebrow: '운영자',
      title: '만드는 사람이 직접 검토하는 소규모 파일럿입니다.',
      text: 'PapayaMusic Lab은 elecpapaya가 운영·관리하는 독립 제품 프로젝트입니다. 파일럿 적합성 검토, 셋업 논의, 제품 피드백을 운영자가 직접 다루며 신청자와 운영자 사이에 리셀러나 외주 영업팀이 없습니다.',
      link: '공개 GitHub 프로필 보기',
    },
    finalCta: { eyebrow: '다음 단계', title: '좋은 곡이 릴리즈 전에 멈추고 있다면, 그 지점부터 확인해 보세요.', text: '필수 4항목 · 약 2분 · 신청만으로 결제가 시작되지 않습니다.', primary: '2분 적합성 확인', secondary: '구매 조건 보기' },
    article: { byline: 'PapayaMusic Lab · 제작 노트', ctaTitle: '릴리즈 작업이 생성보다 오래 걸리나요?', ctaText: 'Windows Founder Pilot이 AI 음악을 고르고, 완성하고, 공개하는 방식에 맞는지 확인하세요.', cta: '2분 적합성 확인', relatedTitle: '함께 읽기' },
    footer: { description: 'AI 음악 릴리즈를 끝내기 위한 로컬 중심 Windows 제작 스위트입니다.', notice: '제품 접근, 지원, 거래 조건은 결제 전에 서면으로 확인합니다.', data: '데이터 처리 안내', terms: '약관', docs: '구매 안내', contact: '문의' },
    pilotPage: {
      platformTitle: '신청 전 확인: 현재 빌드는 Windows 전용입니다.',
      platformText: '실제로 사용할 PC를 선택해 주세요. 다른 플랫폼도 관심을 남길 수 있지만 현재 유료 접근은 제공하지 않습니다.',
      operatingSystemPrompt: '이 파일럿에 사용할 기기 선택',
      operatingSystems: [['Windows 11', 'Windows 11'], ['기타 Windows · 호환성 확인 필요', 'Other Windows'], ['macOS · 관심 등록만 가능', 'macOS waitlist'], ['기타 플랫폼 · 관심 등록만 가능', 'Other platform waitlist']],
    },
    dataHandling: {
      eyebrow: '데이터 처리 안내', title: '공개 웹사이트가 수집하는 정보와 목적.',
      lead: '이 페이지는 현재 문의 및 Founder Pilot 신청 폼의 처리를 설명합니다. 유료 제품 접근 시 제공되는 별도 조건을 대신하지 않습니다.',
      updated: '최종 업데이트: 2026년 7월 16일',
      sections: [
        ['직접 입력하는 정보', ['문의 폼은 입력한 이름, 답변받을 이메일, 문의 유형, 문의 내용을 수집합니다.', 'Founder Pilot 신청은 역할, 사용할 운영체제, 카탈로그 규모, 사용 도구, 병목, 목표, 기타 메모, 선택적인 증거 후속 연락 의사를 추가로 받을 수 있습니다.', '증거 후속 연락 동의는 나중에 문의할 수 있다는 뜻일 뿐입니다. 별도 검토와 명시적 승인 없이는 파일럿 결과를 공개하지 않습니다.', '어떤 페이지에서 문의가 발생했는지 이해하기 위해 현재 페이지 경로, 캠페인 매개변수, 이전 페이지 경로를 함께 보낼 수 있습니다.']],
        ['사용 목적', ['제출 내용은 자동화된 접근을 검사하고 전송 횟수를 제한한 뒤 PapayaMusic Lab의 비공개 문의 수신처로 전달됩니다.', '답변, 파일럿 적합성 판단, 지원 범위 확인, 판매 흐름 개선에 사용합니다.', '실제 수신 이메일 주소는 페이지 소스에 공개하지 않습니다.']],
        ['집계형 이용 흐름 측정', ['페이지·제품 보기, 버튼 클릭, 폼 작성 시작, 운영체제 범주, 제출 결과와 같은 이벤트를 쿠키 없이 기록합니다.', '이벤트에는 언어, 쿼리를 제외한 페이지 경로, 통제된 범주명만 포함합니다. 폼 내용, 이름, 이메일, 전체 이전 페이지 URL, 쿠키, 지속적인 사용자 식별자는 포함하지 않습니다.', '집계 이벤트 행은 Cloudflare D1에 저장하며 이벤트 수집 시 90일이 지난 행을 삭제합니다.']],
        ['외부 서비스와 주의사항', ['Cloudflare Turnstile은 Cloudflare의 자체 약관과 개인정보 문서에 따라 보안 확인 데이터를 처리합니다.', '비밀번호, OAuth 파일, 비공개 토큰, 미공개 고객 데이터, 기밀 미디어를 폼으로 보내지 마세요.', '제품의 로컬 데이터 처리와 유료 접근 조건은 결제 전에 별도로 설명합니다.']],
        ['선택권', ['이전에 제출한 내용의 확인, 수정, 삭제를 문의 폼으로 요청할 수 있습니다.', '선택 제작 항목을 보내고 싶지 않다면 비워둘 수 있습니다.', '폼 제출만으로 결제나 파일럿 자동 갱신이 발생하지 않습니다.']],
      ],
      contactCta: '데이터 처리 문의',
    },
  },
  ja: {
    productName: 'PapayaMusic Lab Studio',
    brandSubtitle: 'Studio',
    nav: { tour: '製品を見る', fit: '適合性', pilot: '価格', faq: 'よくある質問', blog: 'ブログ', docs: '購入ガイド' },
    a11y: { home: 'PapayaMusic Labホーム', primaryNav: 'メインナビゲーション', language: '言語選択', footerNav: 'フッターナビゲーション' },
    hero: {
      eyebrow: 'AI音楽を継続的にリリースするソロ制作者と小規模スタジオへ',
      title: '良いAI楽曲ができたら、リリースまで仕上げる。',
      lead: 'PapayaMusic Lab Studioは、候補選定、マスタリング確認、配信情報、ミュージックビデオ、YouTube準備を一つのローカルWindows制作フローでつなぎます。',
      primaryCta: '90秒の制作フローを見る', secondaryCta: '自分の作業に合うか確認', platform: 'Founder Pilot · Windows 11',
      proof: ['未公開の音源と映像はローカル保持', '既存のSuno・REAPER・DistroKid・YouTubeアカウントを利用', '選定・権利・最終送信は自分で承認'],
    },
    tour: {
      eyebrow: '90秒の制作フロー', title: '曲を選び、確認し、リリースまで仕上げる。',
      lead: 'ツールが変わるたびに整理し直さないよう、判断根拠と準備状態を次の作業へ引き継ぎます。', previewLabel: '製品フロー例 · ダミーデータ',
      stages: [
        { step: '01', title: '仕上げる価値のある曲だけ残す', text: '生成結果を確認してリリース候補を選び、次へ進めた理由も残します。', screenTitle: '候補レビュー', status: 'リリース候補8曲', rows: [['トラック評価', 'S / A / B'], ['制作コンテキスト', '保存済み'], ['次の作業', '確認可能']] },
        { step: '02', title: 'マスターと配信情報を確認する', text: 'マスタリング数値、ファイル名、メタデータ、クレジット、不足資料を引き渡し前に確認します。', screenTitle: 'リリース準備', status: '5項目中4項目完了', rows: [['マスタリングQC', '準備'], ['配信メタデータ', 'レビュー'], ['権利・クレジット', '本人確認']] },
        { step: '03', title: '公開準備まで完了する', text: '配信サービスへの引き渡し、MV、YouTube資料を準備し、最終送信は自分で承認します。', screenTitle: '公開パッケージ', status: '最終承認前', rows: [['DistroKid引き渡し', '準備'], ['ミュージックビデオ', '承認'], ['YouTube文面', 'レビュー']] },
      ],
      disclosure: 'ダミーデータを使った製品フロー例です。詳細はパイロット中に変更される場合があります。',
    },
    fit: {
      eyebrow: '対象ユーザー', title: 'この問題が繰り返される人に最も適しています。', lead: '毎月AI音楽を作っていても、完成したリリースより候補と後工程のほうが速く増える人のためのパイロットです。',
      goodTitle: '適している可能性が高い', goodItems: ['通常、月に30曲前後以上の生成候補を管理している。', '選別、ノート、メディア、公開準備がフォルダ、チャット、表計算に散らばっている。', 'Windowsのローカル運用を望み、創作と公開の最終承認は自分で行いたい。'],
      notTitle: 'まだ適していない可能性', notItems: ['音楽生成器、DAW、ディストリビューター、または制作代行が必要である。', '主な端末がmacOSまたはモバイルである。現在のパイロットビルドはWindowsのみです。', '生成は時々だけで、生成後の反復的なボトルネックをまだ感じていない。'],
    },
    offer: {
      eyebrow: 'Founder Pilotの提案', title: '最初の30日で、実際のリリースフローを一度確認します。', lead: '申込は決済ではなく適合確認です。使用するWindows PC、支援範囲、アクセス方法、書面条件を確認してからのみ支払いを案内します。', price: 'USD 199', period: '最初の30日',
      terms: [['継続利用', '追加30日ごとにUSD 69'], ['更新', '手動選択のみ · 自動請求なし'], ['プラットフォーム', 'Windowsデスクトップ · 支払い前に互換性確認']],
      includesTitle: '最初の30日に含まれる内容', includes: ['Windows PCと既存ツールの適合確認', '支払い後の保護されたWindowsビルドとライセンス', 'ローカル作業フォルダと必須ツールのセットアップ支援', '実際の制作フロー1回のレビュー'],
      processTitle: '申込後の流れ', process: [['1', '申込', 'ボトルネック、制作量、使用するWindows PCを共有します。'], ['2', '確認', '適合性、価格、支援、アクセス、返金条件を書面で受け取ります。'], ['3', '開始', '条件に同意する場合だけ支払い、保護されたアクセスとセットアップ案内を受け取ります。'], ['4', 'レビュー', '実制作1回を行い、次の30日間に価値があるか判断します。']],
      note: '端末、継続利用、支援、返金の詳細は、支払い前に提供される書面の提案が基準です。', cta: 'Founder Pilotに申し込む',
    },
    faq: {
      eyebrow: '購入前のよくある質問', title: '相談前に確認できる回答です。',
      items: [
        ['PapayaMusic Lab Studioは音楽生成器ですか？', 'いいえ。既存ツール間の候補レビュー、マスタリング根拠、配信メタデータ、MV制作、公開準備をつなぎます。'],
        ['どのOSに対応していますか？', '現在のパイロットビルドはWindowsデスクトップのみです。正確なWindowsバージョンとPC互換性は支払い前に確認します。macOSとモバイル版は現在提供していません。'],
        ['何が自分のPCに残りますか？', '未公開音源、歌詞、映像、プロジェクトファイル、ローカルパス、ブラウザセッション、外部サービスの資格情報は、限定された診断情報を支援用に明示的に書き出さない限り基本的にローカルに残ります。'],
        ['Suno、ChatGPT、REAPER、配信、映像のアカウントも含まれますか？', 'いいえ。既存のアカウントとライセンスを使用します。ツール名はワークフローの互換性を説明するもので、公式提携を意味しません。'],
        ['USD 199には何が含まれますか？', '最初の30日には、適合確認、支払い後の保護されたアクセス、ライセンス有効化、セットアップ支援、制作作業1回のレビューが含まれます。'],
        ['30日後はどうなりますか？', '自動更新はありません。継続利用は30日ごとにUSD 69で手動延長できます。正確なアクセスと更新条件は支払い前の書面提案で確認します。'],
        ['返金ポリシーは？', '適用される返金条件は支払い前の書面提案に記載します。条件を確認し同意するまでは支払いを求めません。'],
        ['支援範囲外は？', '無制限の制作代行、法務助言、外部アカウント管理、AI出力品質の保証は範囲外です。'],
      ],
    },
    operator: {
      eyebrow: '運営者',
      title: '作り手が直接確認する、小規模なパイロットです。',
      text: 'PapayaMusic Labは、elecpapayaが運営・管理する独立した製品プロジェクトです。パイロット適合性の確認、セットアップ相談、製品フィードバックは運営者が直接扱い、申込者との間に再販業者や外部営業チームは入りません。',
      link: '公開GitHubプロフィールを見る',
    },
    finalCta: { eyebrow: '次のステップ', title: '良い曲がリリース前で止まっているなら、そこから確認してください。', text: '必須4項目 · 約2分 · 申込だけで決済は始まりません。', primary: '2分で適合性を確認', secondary: '購入条件を見る' },
    article: { byline: 'PapayaMusic Lab · 制作ノート', ctaTitle: 'リリース作業が生成より長くかかっていますか？', ctaText: 'Windows Founder PilotがAI音楽を選び、仕上げ、公開する方法に合うか確認してください。', cta: '2分で適合性を確認', relatedTitle: '関連記事' },
    footer: { description: 'AI音楽リリースを仕上げるためのローカル中心Windows制作スイートです。', notice: '製品アクセス、支援、取引条件は支払い前に書面で確認します。', data: 'データ取扱い', terms: '利用規約', docs: '購入ガイド', contact: 'お問い合わせ' },
    pilotPage: {
      platformTitle: '申込前の確認: 現在のビルドはWindowsのみです。', platformText: '実際に使用するPCを選択してください。他のプラットフォームも関心を登録できますが、現在は有料アクセスを提供していません。', operatingSystemPrompt: 'このパイロットで使用する端末を選択',
      operatingSystems: [['Windows 11', 'Windows 11'], ['その他のWindows · 互換性確認が必要', 'Other Windows'], ['macOS · 関心登録のみ', 'macOS waitlist'], ['その他のプラットフォーム · 関心登録のみ', 'Other platform waitlist']],
    },
    dataHandling: {
      eyebrow: 'データ取扱い', title: '公開サイトが収集する情報と目的。', lead: 'このページは現在のお問い合わせフォームとFounder Pilot申込フォームの処理を説明します。有料製品アクセス時に提供される別条件の代わりではありません。', updated: '最終更新: 2026年7月16日',
      sections: [
        ['入力する情報', ['お問い合わせフォームは、入力した名前、返信先メール、問い合わせ種別、内容を収集します。', 'Founder Pilot申込では、役割、使用OS、カタログ規模、ツール、ボトルネック、目標、メモ、任意の証拠フォローアップ希望も入力できます。', '証拠フォローアップへの同意は、後日質問できるという意味だけです。別途の確認と明示的な承認なしにパイロット結果を公開することはありません。', 'どのページから問い合わせにつながったか理解するため、現在のページパス、キャンペーンパラメータ、参照ページのパスを添付する場合があります。']],
        ['利用目的', ['送信内容は自動化されたアクセスを確認し、送信回数を制限した後、PapayaMusic Labの非公開の問い合わせ先へ転送されます。', '返信、パイロット適合性の判断、支援範囲の確認、販売導線の改善に使用します。', '実際の受信メールアドレスはページソースに公開しません。']],
        ['集計型の利用動線計測', ['ページや製品ツアーの表示、CTAのクリック、フォーム入力開始、OSカテゴリー、送信結果などのイベントをCookieなしで記録します。', 'イベントには言語、クエリを除いたページパス、管理されたカテゴリー名だけを含めます。フォーム内容、氏名、メールアドレス、完全な参照URL、Cookie、永続的なユーザー識別子は含めません。', '集計イベント行はCloudflare D1に保存し、イベント収集時に90日を超えた行を削除します。']],
        ['外部サービスと注意事項', ['Cloudflare Turnstileは、Cloudflare自身の規約とプライバシー文書に基づきセキュリティ確認データを処理します。', 'パスワード、OAuthファイル、private token、未公開の顧客データ、機密メディアをフォームで送信しないでください。', '製品のローカルデータ処理と有料アクセス条件は支払い前に別途説明します。']],
        ['選択肢', ['以前に送信した内容の確認、修正、削除をお問い合わせフォームから依頼できます。', '任意の制作項目は空欄のまま送信できます。', 'フォーム送信だけで決済やパイロットの自動更新が発生することはありません。']],
      ],
      contactCta: 'データ取扱いについて問い合わせる',
    },
  },
};

export function getSalesContent(language) {
  return salesContent[language] ?? salesContent.en;
}
