const salesContent = {
  en: {
    productName: 'PapayaMusic Lab Studio',
    brandSubtitle: 'Studio',
    nav: {
      tour: 'Product tour',
      fit: 'Fit',
      pilot: 'Pricing',
      faq: 'FAQ',
      blog: 'Blog',
      docs: 'Buyer guide',
    },
    a11y: {
      home: 'PapayaMusic Lab home',
      primaryNav: 'Primary navigation',
      language: 'Language selector',
      footerNav: 'Footer navigation',
    },
    hero: {
      eyebrow: 'Windows desktop · local-first · human-approved',
      title: 'Finish the AI-generated songs worth releasing.',
      lead:
        'PapayaMusic Lab Studio organizes the work after generation—selection, review context, media materials, and release readiness—for operators managing a growing catalog.',
      primaryCta: 'See the product flow',
      secondaryCta: 'Check Founder Pilot fit',
      platform: 'Current pilot: Windows desktop only',
      proof: ['Unreleased media stays local by default', 'Bring your existing tools and accounts', 'No automatic pilot renewal'],
    },
    tour: {
      eyebrow: '90-second product tour',
      title: 'One production record from candidate pile to release review.',
      lead:
        'The public preview uses dummy project data and shows the operating idea without exposing the protected build or private implementation details.',
      previewLabel: 'Illustrative interface preview · dummy data',
      stages: [
        {
          step: '01',
          title: 'Narrow the candidate queue',
          text: 'Keep the strongest tracks visible and record why each one should move forward.',
          screenTitle: 'Candidate queue',
          status: '37 candidates · 8 shortlisted',
          rows: [
            ['Glass Harbor', 'Shortlist'],
            ['Neon Orchard', 'Review'],
            ['After Rain', 'Hold'],
          ],
        },
        {
          step: '02',
          title: 'Carry review context forward',
          text: 'Keep the next action, approval state, and production notes attached to the release record.',
          screenTitle: 'Review record',
          status: 'Human approval required',
          rows: [
            ['Arrangement', 'Approved'],
            ['Master note', 'Ready'],
            ['Artwork', 'Needs review'],
          ],
        },
        {
          step: '03',
          title: 'Check the release package',
          text: 'See which media and publishing materials are ready before the operator approves delivery.',
          screenTitle: 'Release package',
          status: '4 of 5 checks complete',
          rows: [
            ['Audio master', 'Ready'],
            ['Video material', 'Ready'],
            ['Publishing copy', 'Review'],
          ],
        },
      ],
      disclosure: 'This is a sales-site illustration, not a screenshot of customer data. Product details may change during the pilot.',
    },
    fit: {
      eyebrow: 'Who it is for',
      title: 'A focused fit check before anyone pays.',
      lead: 'Founder Pilot is intentionally narrow. It works best when post-generation work is already a recurring operational bottleneck.',
      goodTitle: 'Likely a good fit',
      goodItems: [
        'You manage roughly 30 or more generated candidates in a typical month.',
        'Selection, notes, media, and publishing readiness are spread across folders, chat, and spreadsheets.',
        'You want a local Windows workflow while keeping final creative and publishing approval human.',
      ],
      notTitle: 'Probably not yet',
      notItems: [
        'You need a music generator, DAW, distributor, or done-for-you production service.',
        'Your main machine is macOS or mobile; the current pilot build is Windows-only.',
        'You generate occasionally and do not yet feel a repeatable post-generation bottleneck.',
      ],
    },
    offer: {
      eyebrow: 'Founder Pilot offer',
      title: 'Know the commercial flow before you apply.',
      lead: 'The application is a fit check, not a checkout. Payment is requested only after the product, machine, support scope, and written terms are confirmed.',
      price: 'USD 199',
      period: 'First 30 days',
      terms: [
        ['Continued access', 'USD 69 per additional 30 days'],
        ['Renewal', 'Manual only; no automatic charge'],
        ['Platform', 'Windows desktop; exact compatibility confirmed before payment'],
      ],
      includesTitle: 'Included in the first 30 days',
      includes: [
        'Fit and support-scope confirmation',
        'Protected download and license after payment',
        'Guided setup',
        'One review of a real production run',
      ],
      processTitle: 'What happens next',
      process: [
        ['1', 'Apply', 'Share the bottleneck, production volume, and target Windows machine.'],
        ['2', 'Confirm', 'Receive a written fit, price, support, access, and refund-terms summary.'],
        ['3', 'Start', 'Pay only if you accept the terms, then receive protected access and setup guidance.'],
        ['4', 'Review', 'Use one real production run to decide whether another 30 days is worthwhile.'],
      ],
      note: 'The written offer provided before payment controls device, continued-access, support, and refund details.',
      cta: 'Apply for Founder Pilot',
    },
    faq: {
      eyebrow: 'Buyer FAQ',
      title: 'Answers before a sales conversation.',
      items: [
        ['Is PapayaMusic Lab Studio another music generator?', 'No. It is designed for the operating work after generation: selection, context, media readiness, and release review.'],
        ['Which platforms are supported?', 'The current pilot build is for Windows desktop. Exact Windows version and machine compatibility are checked before payment. macOS and mobile access are not offered in the current pilot.'],
        ['What stays on my computer?', 'Unreleased audio, lyrics, video clips, project files, local paths, browser sessions, and third-party credentials stay local by default unless you explicitly export limited diagnostics for support.'],
        ['Are Suno, ChatGPT, REAPER, distribution, or video accounts included?', 'No. You bring your own accounts and licenses. Tool names describe workflow compatibility and do not imply a partnership.'],
        ['What does USD 199 include?', 'The first 30 days include the fit confirmation, protected access after payment, license activation, guided setup, and one supported production review.'],
        ['What happens after 30 days?', 'There is no automatic renewal. Continued access can be extended manually at USD 69 per 30 days. The written offer confirms the exact access and update terms before payment.'],
        ['What is the refund policy?', 'The applicable refund conditions are stated in the written offer before payment. No payment is requested until you have reviewed and accepted those terms.'],
        ['What is outside support scope?', 'Unlimited production labor, legal advice, third-party account administration, and guaranteed AI output quality are outside the pilot scope.'],
      ],
    },
    finalCta: {
      eyebrow: 'Next step',
      title: 'Bring one real bottleneck—not a polished pitch.',
      text: 'The short application helps determine whether the Windows pilot can make a measurable difference in your current production flow.',
      primary: 'Start the fit check',
      secondary: 'Read the buyer guide',
    },
    article: {
      byline: 'PapayaMusic Lab · Production note',
      ctaTitle: 'Is post-generation work already the bottleneck?',
      ctaText: 'See the product flow and check whether the Windows Founder Pilot fits your current catalog operation.',
      cta: 'Check pilot fit',
      relatedTitle: 'Continue reading',
    },
    footer: {
      description: 'A local-first Windows production workspace for the work after AI music generation.',
      notice: 'Product access, support, and commercial terms are confirmed in writing before payment.',
      data: 'Data handling',
      terms: 'Terms',
      docs: 'Buyer guide',
      contact: 'Contact',
    },
    pilotPage: {
      platformTitle: 'Before you apply: the current build is Windows-only.',
      platformText: 'Choose the machine you plan to use. Other platforms can still submit interest, but paid access is not currently offered for them.',
      operatingSystemPrompt: 'Choose the machine for this pilot',
      operatingSystems: [
        ['Windows 11', 'Windows 11'],
        ['Other Windows — compatibility check needed', 'Other Windows'],
        ['macOS — interest only, no current build', 'macOS waitlist'],
        ['Other platform — interest only', 'Other platform waitlist'],
      ],
    },
    dataHandling: {
      eyebrow: 'Data handling',
      title: 'What the public website collects and why.',
      lead: 'This page describes the current contact and Founder Pilot forms. It is a practical data-handling notice, not a substitute for terms provided with paid product access.',
      updated: 'Last updated: July 16, 2026',
      sections: [
        ['Information you submit', ['Contact forms collect the name, reply email, inquiry type, and message you enter.', 'Founder Pilot applications may also collect role, target operating system, catalog volume, tools, bottleneck, goals, and notes.', 'The site may attach the page path, campaign parameters, and referring page path to understand which page led to the inquiry.']],
        ['How it is used', ['Submissions are checked for automated abuse, rate-limited, and forwarded to the private PapayaMusic Lab contact recipient.', 'The information is used to reply, assess pilot fit, clarify support scope, and improve the sales journey.', 'The website does not expose the destination email address in page source.']],
        ['Service boundaries', ['Cloudflare Turnstile processes security-check data under Cloudflare’s own terms and privacy documentation.', 'Do not submit passwords, OAuth files, private tokens, unreleased customer data, or confidential media through these forms.', 'Product-local data handling and paid-access terms are explained separately before payment.']],
        ['Your choices', ['You may ask what you previously submitted or request correction or deletion by using the contact form.', 'If you do not want to send the optional production fields, leave them blank.', 'No automatic payment or pilot renewal is triggered by submitting a form.']],
      ],
      contactCta: 'Ask a data-handling question',
    },
  },
  ko: {
    productName: 'PapayaMusic Lab Studio',
    brandSubtitle: 'Studio',
    nav: { tour: '제품 보기', fit: '적합성', pilot: '가격', faq: '자주 묻는 질문', blog: '블로그', docs: '구매 안내' },
    a11y: { home: 'PapayaMusic Lab 홈', primaryNav: '주요 메뉴', language: '언어 선택', footerNav: '하단 메뉴' },
    hero: {
      eyebrow: 'Windows 데스크톱 · 로컬 중심 · 사람의 최종 승인',
      title: 'AI로 생성한 곡 중, 릴리즈할 가치가 있는 곡을 끝까지 완성하세요.',
      lead: 'PapayaMusic Lab Studio는 생성 이후의 선별, 리뷰 맥락, 미디어 자료, 릴리즈 준비 상태를 한곳에 정리하는 카탈로그 운영 도구입니다.',
      primaryCta: '제품 흐름 90초 보기',
      secondaryCta: 'Founder Pilot 적합성 확인',
      platform: '현재 파일럿: Windows 데스크톱 전용',
      proof: ['미공개 미디어는 기본적으로 로컬에 유지', '기존 도구와 계정을 그대로 사용', '파일럿 자동 갱신 없음'],
    },
    tour: {
      eyebrow: '90초 제품 흐름',
      title: '쌓인 후보부터 릴리즈 검토까지, 하나의 제작 기록으로 이어집니다.',
      lead: '공개 미리보기는 더미 프로젝트 데이터로 제품의 운영 방식을 보여줍니다. 보호된 빌드와 비공개 구현 정보는 공개하지 않습니다.',
      previewLabel: '설명용 인터페이스 미리보기 · 더미 데이터',
      stages: [
        { step: '01', title: '후보 목록을 좁힙니다', text: '강한 후보만 남기고, 왜 다음 단계로 보내는지 판단 근거를 기록합니다.', screenTitle: '후보 목록', status: '후보 37개 · 선별 8개', rows: [['Glass Harbor', '선별'], ['Neon Orchard', '검토'], ['After Rain', '보류']] },
        { step: '02', title: '리뷰 맥락을 이어갑니다', text: '다음 행동, 승인 상태, 제작 노트를 릴리즈 기록에 붙여 다음 세션에서 바로 이어갑니다.', screenTitle: '리뷰 기록', status: '사람의 승인 필요', rows: [['편곡', '승인'], ['마스터 노트', '준비'], ['아트워크', '검토 필요']] },
        { step: '03', title: '릴리즈 패키지를 확인합니다', text: '운영자가 전달을 승인하기 전에 미디어와 공개 자료의 준비 상태를 확인합니다.', screenTitle: '릴리즈 패키지', status: '5개 중 4개 완료', rows: [['오디오 마스터', '준비'], ['영상 자료', '준비'], ['공개 문구', '검토']] },
      ],
      disclosure: '고객 데이터 화면이 아닌 판매 페이지용 설명 이미지입니다. 세부 제품은 파일럿 과정에서 달라질 수 있습니다.',
    },
    fit: {
      eyebrow: '누구에게 맞는가', title: '결제 전에 좁고 명확하게 적합성을 확인합니다.',
      lead: 'Founder Pilot은 의도적으로 대상이 좁습니다. 생성 이후 작업이 이미 반복적인 운영 병목일 때 가장 잘 맞습니다.',
      goodTitle: '잘 맞을 가능성이 높습니다',
      goodItems: ['평균적으로 월 30개 안팎 이상의 생성 후보를 관리합니다.', '선별, 노트, 미디어, 공개 준비가 폴더·채팅·스프레드시트에 흩어져 있습니다.', 'Windows 로컬 흐름을 원하며 창작과 공개의 최종 승인은 직접 하고 싶습니다.'],
      notTitle: '아직은 맞지 않을 수 있습니다',
      notItems: ['음악 생성기, DAW, 배급사 또는 제작 대행 서비스가 필요합니다.', '주 사용 기기가 macOS나 모바일입니다. 현재 파일럿 빌드는 Windows 전용입니다.', '가끔 생성하며 생성 이후 반복 병목을 아직 느끼지 않습니다.'],
    },
    offer: {
      eyebrow: 'Founder Pilot 제안', title: '신청하기 전에 가격과 진행 순서를 확인하세요.',
      lead: '신청은 결제가 아니라 적합성 확인입니다. 제품, 사용할 PC, 지원 범위, 서면 조건을 확인한 뒤에만 결제를 요청합니다.',
      price: 'USD 199', period: '첫 30일',
      terms: [['계속 사용', '추가 30일마다 USD 69'], ['갱신', '수동 선택만 가능 · 자동 결제 없음'], ['플랫폼', 'Windows 데스크톱 · 결제 전 호환성 확인']],
      includesTitle: '첫 30일 포함 내용',
      includes: ['적합성과 지원 범위 확인', '결제 후 보호된 다운로드와 라이선스', '가이드 셋업', '실제 제작 작업 1회 리뷰'],
      processTitle: '신청 후 진행',
      process: [['1', '신청', '병목, 제작 규모, 사용할 Windows PC를 공유합니다.'], ['2', '확인', '적합성, 가격, 지원, 접근, 환불 조건을 서면으로 받습니다.'], ['3', '시작', '조건에 동의할 때만 결제하고 보호된 접근과 셋업 안내를 받습니다.'], ['4', '검토', '실제 제작 1회를 수행한 뒤 다음 30일이 가치 있는지 판단합니다.']],
      note: '기기, 계속 사용, 지원, 환불의 세부 조건은 결제 전에 제공되는 서면 제안이 기준입니다.', cta: 'Founder Pilot 신청',
    },
    faq: {
      eyebrow: '구매 전 자주 묻는 질문', title: '상담 전에 먼저 확인할 답변입니다.',
      items: [
        ['PapayaMusic Lab Studio는 음악 생성기인가요?', '아닙니다. 생성 이후의 선별, 맥락 유지, 미디어 준비, 릴리즈 검토를 위한 운영 도구입니다.'],
        ['어떤 운영체제를 지원하나요?', '현재 파일럿 빌드는 Windows 데스크톱 전용입니다. 정확한 Windows 버전과 PC 호환성은 결제 전에 확인합니다. macOS와 모바일 빌드는 현재 제공하지 않습니다.'],
        ['무엇이 내 컴퓨터에 남나요?', '미공개 음원, 가사, 영상 클립, 프로젝트 파일, 로컬 경로, 브라우저 세션, 외부 서비스 자격 정보는 제한된 진단 정보를 지원용으로 직접 내보내지 않는 한 기본적으로 로컬에 남습니다.'],
        ['Suno, ChatGPT, REAPER, 배급이나 영상 계정도 포함되나요?', '아닙니다. 기존 계정과 라이선스를 사용합니다. 도구명은 작업 흐름의 호환성을 설명하며 공식 제휴를 의미하지 않습니다.'],
        ['USD 199에 무엇이 포함되나요?', '첫 30일의 적합성 확인, 결제 후 보호된 접근, 라이선스 활성화, 가이드 셋업, 제작 작업 1회 리뷰가 포함됩니다.'],
        ['30일 뒤에는 어떻게 되나요?', '자동 갱신은 없습니다. 계속 사용은 30일마다 USD 69로 직접 연장할 수 있습니다. 정확한 접근과 업데이트 조건은 결제 전 서면 제안에서 확인합니다.'],
        ['환불 정책은 무엇인가요?', '적용되는 환불 조건은 결제 전에 서면 제안에 명시합니다. 조건을 검토하고 동의하기 전에는 결제를 요청하지 않습니다.'],
        ['지원 범위에 포함되지 않는 것은 무엇인가요?', '무제한 제작 대행, 법률 자문, 외부 계정 관리, AI 결과물 품질 보장은 파일럿 지원 범위 밖입니다.'],
      ],
    },
    finalCta: { eyebrow: '다음 단계', title: '잘 다듬은 소개 대신, 실제 병목 하나를 알려주세요.', text: '짧은 신청을 통해 Windows 파일럿이 현재 제작 흐름에 측정 가능한 차이를 만들 수 있는지 확인합니다.', primary: '적합성 확인 시작', secondary: '구매 안내 읽기' },
    article: { byline: 'PapayaMusic Lab · 제작 노트', ctaTitle: '생성 이후 작업이 이미 병목인가요?', ctaText: '제품 흐름을 보고 Windows Founder Pilot이 현재 카탈로그 운영에 맞는지 확인하세요.', cta: '파일럿 적합성 확인', relatedTitle: '함께 읽기' },
    footer: { description: 'AI 음악 생성 이후 작업을 위한 로컬 중심 Windows 제작 도구입니다.', notice: '제품 접근, 지원, 거래 조건은 결제 전에 서면으로 확인합니다.', data: '데이터 처리 안내', terms: '약관', docs: '구매 안내', contact: '문의' },
    pilotPage: {
      platformTitle: '신청 전 확인: 현재 빌드는 Windows 전용입니다.',
      platformText: '실제로 사용할 PC를 선택해 주세요. 다른 플랫폼도 관심을 남길 수 있지만 현재 유료 접근은 제공하지 않습니다.',
      operatingSystemPrompt: '이 파일럿에 사용할 기기 선택',
      operatingSystems: [['Windows 11', 'Windows 11'], ['기타 Windows · 호환성 확인 필요', 'Other Windows'], ['macOS · 관심 등록만 가능', 'macOS waitlist'], ['기타 플랫폼 · 관심 등록만 가능', 'Other platform waitlist']],
    },
    dataHandling: {
      eyebrow: '데이터 처리 안내', title: '공개 웹사이트가 수집하는 정보와 목적.',
      lead: '이 페이지는 현재 문의 및 Founder Pilot 신청 폼의 처리를 설명합니다. 유료 제품 접근 시 제공되는 별도 조건을 대신하지 않습니다.',
      updated: '최종 업데이트: 2026년 7월 16일',
      sections: [
        ['직접 입력하는 정보', ['문의 폼은 입력한 이름, 답변받을 이메일, 문의 유형, 문의 내용을 수집합니다.', 'Founder Pilot 신청은 역할, 사용할 운영체제, 카탈로그 규모, 사용 도구, 병목, 목표, 기타 메모를 추가로 받을 수 있습니다.', '어떤 페이지에서 문의가 발생했는지 이해하기 위해 현재 페이지 경로, 캠페인 매개변수, 이전 페이지 경로를 함께 보낼 수 있습니다.']],
        ['사용 목적', ['제출 내용은 자동화된 접근을 검사하고 전송 횟수를 제한한 뒤 PapayaMusic Lab의 비공개 문의 수신처로 전달됩니다.', '답변, 파일럿 적합성 판단, 지원 범위 확인, 판매 흐름 개선에 사용합니다.', '실제 수신 이메일 주소는 페이지 소스에 공개하지 않습니다.']],
        ['외부 서비스와 주의사항', ['Cloudflare Turnstile은 Cloudflare의 자체 약관과 개인정보 문서에 따라 보안 확인 데이터를 처리합니다.', '비밀번호, OAuth 파일, 비공개 토큰, 미공개 고객 데이터, 기밀 미디어를 폼으로 보내지 마세요.', '제품의 로컬 데이터 처리와 유료 접근 조건은 결제 전에 별도로 설명합니다.']],
        ['선택권', ['이전에 제출한 내용의 확인, 수정, 삭제를 문의 폼으로 요청할 수 있습니다.', '선택 제작 항목을 보내고 싶지 않다면 비워둘 수 있습니다.', '폼 제출만으로 결제나 파일럿 자동 갱신이 발생하지 않습니다.']],
      ],
      contactCta: '데이터 처리 문의',
    },
  },
  ja: {
    productName: 'PapayaMusic Lab Studio',
    brandSubtitle: 'Studio',
    nav: { tour: '製品を見る', fit: '適合性', pilot: '価格', faq: 'よくある質問', blog: 'ブログ', docs: '購入ガイド' },
    a11y: { home: 'PapayaMusic Labホーム', primaryNav: 'メインナビゲーション', language: '言語選択', footerNav: 'フッターナビゲーション' },
    hero: {
      eyebrow: 'Windowsデスクトップ · ローカル中心 · 人による最終承認',
      title: 'AI生成曲の中から、リリースする価値のある曲を最後まで仕上げる。',
      lead: 'PapayaMusic Lab Studioは、生成後の選別、レビュー文脈、メディア資料、リリース準備状態を一か所に整理するカタログ運用ツールです。',
      primaryCta: '90秒の製品フローを見る', secondaryCta: 'Founder Pilotの適合性を確認', platform: '現在のパイロット: Windowsデスクトップのみ',
      proof: ['未公開メディアは基本的にローカル保持', '既存のツールとアカウントを利用', 'パイロットの自動更新なし'],
    },
    tour: {
      eyebrow: '90秒の製品フロー', title: '積み上がった候補からリリースレビューまで、一つの制作記録でつなぐ。',
      lead: '公開プレビューはダミーのプロジェクトデータで運用の考え方を示します。保護されたビルドや非公開の実装情報は公開しません。', previewLabel: '説明用インターフェース · ダミーデータ',
      stages: [
        { step: '01', title: '候補リストを絞る', text: '強い候補を残し、次へ進める理由を記録します。', screenTitle: '候補リスト', status: '候補37曲 · 選別8曲', rows: [['Glass Harbor', '選別'], ['Neon Orchard', 'レビュー'], ['After Rain', '保留']] },
        { step: '02', title: 'レビュー文脈を引き継ぐ', text: '次の行動、承認状態、制作ノートをリリース記録に付けて次のセッションへつなぎます。', screenTitle: 'レビュー記録', status: '人の承認が必要', rows: [['アレンジ', '承認'], ['マスターノート', '準備'], ['アートワーク', '要レビュー']] },
        { step: '03', title: 'リリースパッケージを確認', text: '運用者が提出を承認する前に、メディアと公開資料の準備状態を確認します。', screenTitle: 'リリースパッケージ', status: '5項目中4項目完了', rows: [['音源マスター', '準備'], ['映像資料', '準備'], ['公開文', 'レビュー']] },
      ],
      disclosure: '顧客データの画面ではなく、販売ページ用の説明イメージです。製品詳細はパイロット中に変更される場合があります。',
    },
    fit: {
      eyebrow: '対象ユーザー', title: '支払い前に、狭く明確な適合確認を行います。', lead: 'Founder Pilotは対象を意図的に絞っています。生成後の作業がすでに反復的な運用ボトルネックである場合に最も適しています。',
      goodTitle: '適している可能性が高い', goodItems: ['通常、月に30曲前後以上の生成候補を管理している。', '選別、ノート、メディア、公開準備がフォルダ、チャット、表計算に散らばっている。', 'Windowsのローカル運用を望み、創作と公開の最終承認は自分で行いたい。'],
      notTitle: 'まだ適していない可能性', notItems: ['音楽生成器、DAW、ディストリビューター、または制作代行が必要である。', '主な端末がmacOSまたはモバイルである。現在のパイロットビルドはWindowsのみです。', '生成は時々だけで、生成後の反復的なボトルネックをまだ感じていない。'],
    },
    offer: {
      eyebrow: 'Founder Pilotの提案', title: '申込前に価格と進行手順を確認。', lead: '申込は決済ではなく適合確認です。製品、使用PC、支援範囲、書面条件を確認してからのみ支払いを案内します。', price: 'USD 199', period: '最初の30日',
      terms: [['継続利用', '追加30日ごとにUSD 69'], ['更新', '手動選択のみ · 自動請求なし'], ['プラットフォーム', 'Windowsデスクトップ · 支払い前に互換性確認']],
      includesTitle: '最初の30日に含まれる内容', includes: ['適合性と支援範囲の確認', '支払い後の保護されたダウンロードとライセンス', 'ガイド付きセットアップ', '実際の制作作業1回のレビュー'],
      processTitle: '申込後の流れ', process: [['1', '申込', 'ボトルネック、制作量、使用するWindows PCを共有します。'], ['2', '確認', '適合性、価格、支援、アクセス、返金条件を書面で受け取ります。'], ['3', '開始', '条件に同意する場合だけ支払い、保護されたアクセスとセットアップ案内を受け取ります。'], ['4', 'レビュー', '実制作1回を行い、次の30日間に価値があるか判断します。']],
      note: '端末、継続利用、支援、返金の詳細は、支払い前に提供される書面の提案が基準です。', cta: 'Founder Pilotに申し込む',
    },
    faq: {
      eyebrow: '購入前のよくある質問', title: '相談前に確認できる回答です。',
      items: [
        ['PapayaMusic Lab Studioは音楽生成器ですか？', 'いいえ。生成後の選別、文脈保持、メディア準備、リリースレビューのための運用ツールです。'],
        ['どのOSに対応していますか？', '現在のパイロットビルドはWindowsデスクトップのみです。正確なWindowsバージョンとPC互換性は支払い前に確認します。macOSとモバイル版は現在提供していません。'],
        ['何が自分のPCに残りますか？', '未公開音源、歌詞、映像、プロジェクトファイル、ローカルパス、ブラウザセッション、外部サービスの資格情報は、限定された診断情報を支援用に明示的に書き出さない限り基本的にローカルに残ります。'],
        ['Suno、ChatGPT、REAPER、配信、映像のアカウントも含まれますか？', 'いいえ。既存のアカウントとライセンスを使用します。ツール名はワークフローの互換性を説明するもので、公式提携を意味しません。'],
        ['USD 199には何が含まれますか？', '最初の30日には、適合確認、支払い後の保護されたアクセス、ライセンス有効化、セットアップ支援、制作作業1回のレビューが含まれます。'],
        ['30日後はどうなりますか？', '自動更新はありません。継続利用は30日ごとにUSD 69で手動延長できます。正確なアクセスと更新条件は支払い前の書面提案で確認します。'],
        ['返金ポリシーは？', '適用される返金条件は支払い前の書面提案に記載します。条件を確認し同意するまでは支払いを求めません。'],
        ['支援範囲外は？', '無制限の制作代行、法務助言、外部アカウント管理、AI出力品質の保証は範囲外です。'],
      ],
    },
    finalCta: { eyebrow: '次のステップ', title: '整えた紹介文ではなく、実際のボトルネックを一つ共有してください。', text: '短い申込で、Windowsパイロットが現在の制作フローに測定可能な違いを作れるか確認します。', primary: '適合確認を始める', secondary: '購入ガイドを読む' },
    article: { byline: 'PapayaMusic Lab · 制作ノート', ctaTitle: '生成後の作業がすでにボトルネックですか？', ctaText: '製品フローを見て、Windows Founder Pilotが現在のカタログ運用に合うか確認してください。', cta: 'パイロット適合性を確認', relatedTitle: '関連記事' },
    footer: { description: 'AI音楽生成後の作業のためのローカル中心Windows制作ツールです。', notice: '製品アクセス、支援、取引条件は支払い前に書面で確認します。', data: 'データ取扱い', terms: '利用規約', docs: '購入ガイド', contact: 'お問い合わせ' },
    pilotPage: {
      platformTitle: '申込前の確認: 現在のビルドはWindowsのみです。', platformText: '実際に使用するPCを選択してください。他のプラットフォームも関心を登録できますが、現在は有料アクセスを提供していません。', operatingSystemPrompt: 'このパイロットで使用する端末を選択',
      operatingSystems: [['Windows 11', 'Windows 11'], ['その他のWindows · 互換性確認が必要', 'Other Windows'], ['macOS · 関心登録のみ', 'macOS waitlist'], ['その他のプラットフォーム · 関心登録のみ', 'Other platform waitlist']],
    },
    dataHandling: {
      eyebrow: 'データ取扱い', title: '公開サイトが収集する情報と目的。', lead: 'このページは現在のお問い合わせフォームとFounder Pilot申込フォームの処理を説明します。有料製品アクセス時に提供される別条件の代わりではありません。', updated: '最終更新: 2026年7月16日',
      sections: [
        ['入力する情報', ['お問い合わせフォームは、入力した名前、返信先メール、問い合わせ種別、内容を収集します。', 'Founder Pilot申込では、役割、使用OS、カタログ規模、ツール、ボトルネック、目標、メモも入力できます。', 'どのページから問い合わせにつながったか理解するため、現在のページパス、キャンペーンパラメータ、参照ページのパスを添付する場合があります。']],
        ['利用目的', ['送信内容は自動化されたアクセスを確認し、送信回数を制限した後、PapayaMusic Labの非公開の問い合わせ先へ転送されます。', '返信、パイロット適合性の判断、支援範囲の確認、販売導線の改善に使用します。', '実際の受信メールアドレスはページソースに公開しません。']],
        ['外部サービスと注意事項', ['Cloudflare Turnstileは、Cloudflare自身の規約とプライバシー文書に基づきセキュリティ確認データを処理します。', 'パスワード、OAuthファイル、private token、未公開の顧客データ、機密メディアをフォームで送信しないでください。', '製品のローカルデータ処理と有料アクセス条件は支払い前に別途説明します。']],
        ['選択肢', ['以前に送信した内容の確認、修正、削除をお問い合わせフォームから依頼できます。', '任意の制作項目は空欄のまま送信できます。', 'フォーム送信だけで決済やパイロットの自動更新が発生することはありません。']],
      ],
      contactCta: 'データ取扱いについて問い合わせる',
    },
  },
};

export function getSalesContent(language) {
  return salesContent[language] ?? salesContent.en;
}
